baseURL = 'https://braunbauen.com/'
languageCode = 'en-us'
title = 'Braun Bauen'

[module]
  [[module.imports]]
    path = 'github.com/hugomods/icons/vendors/feather'
  [[module.imports]]
    path = 'github.com/hugomods/icons/vendors/font-awesome'
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "node_modules/alpinejs/dist/module.esm.min.js"
    target = "assets/js/alpinejs.min.js"
  [[module.mounts]]
    source = "node_modules"
    target = "assets"

[params]
  [params.icons]
    throw_on_error = true
